# Generated by Django 2.1.2 on 2019-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190626_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='q_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='q_correct',
            field=models.IntegerField(default=0),
        ),
    ]
